version: '3'

tasks:
  default:
    cmds:
      - task --list-all

  sync:
    internal: true
    cmds:
      - rsync -avr {{.TASKFILE_DIR}}/src/ ${QMK_HOME}/

  build:
    internal: true
    vars:
      PARALLEL:
        sh: nproc
    requires:
      vars:
        - KEYBOARD
        - KEYMAP
    deps:
      - sync
    cmds:
      - qmk compile -e BUILD_DIR={{.TASKFILE_DIR}}/.build -j {{.PARALLEL}} --keyboard {{.KEYBOARD}} --keymap {{.KEYMAP}}

  clean:
    cmds:
      # .build 自体を消すとバインドマウントしているホスト側でファイルの変更が反映されない
      - find .build -mindepth 1 ! -name .gitignore -print0 | xargs --null rm -rf
