# cspell: disable
---
version: '3'

tasks:
  default: task --list-all

  # .build 自体を消すとバインドマウントしているホスト側でファイルの変更が反映されない
  clean: find .build -mindepth 1 ! -name .gitignore -print0 | xargs --null rm -rf

  sync:
    internal: true
    cmd: rsync -avr {{.TASKFILE_DIR}}/src/ ${QMK_HOME}/

  build:*:*:
    vars:
      KEYBOARD: '{{index .MATCH 0}}'
      KEYMAP: '{{index .MATCH 1}}'
      PARALLEL:
        sh: nproc
    deps:
      - sync
    cmd: qmk compile -e BUILD_DIR={{.TASKFILE_DIR}}/.build -j {{.PARALLEL}} -kb {{.KEYBOARD}} -km {{.KEYMAP}}

  build:crkbd:
    cmds:
      - task: build:crkbd/rev1:efumaxay
      - task: draw:crkbd/rev1:efumaxay

  build:crkbd:rev4_0:
    cmds:
      - task: build:foostan/crkbd/rev4_0/standard:efumaxay

  build:lulu:
    cmd:
      task: build:boardsource/lulu/rp2040:efumaxay

  build:lulu:minecraft:
    cmd:
      task: build:boardsource/lulu/rp2040:minecraft

  draw:*:*:
    vars:
      KEYBOARD: '{{index .MATCH 0}}'
      KEYMAP: '{{index .MATCH 1}}'
    cmd: docker compose run --rm -it keymap draw src/keyboards/{{.KEYBOARD}}/keymaps/{{.KEYMAP}}/keymap.yml > src/keyboards/{{.KEYBOARD}}/keymaps/{{.KEYMAP}}/keymap.svg
