VPATH += keyboards/gboards/

BOOTMAGIC_ENABLE = no

KEY_OVERRIDE_ENABLE = yes
TAP_DANCE_ENABLE = yes
COMBO_ENABLE = yes
HOME_ROW_COMBO_ENABLE = yes
CAPS_WORD_ENABLE = yes
NUM_WORD_ENABLE = yes
SUPER_TAB_ENABLE = yes

OLED_ENABLE = no
ENCODER_ENABLE = no

RGB_MATRIX_ENABLE = yes
