#pragma once

#define TAPPING_TERM 200
#define TAPPING_TERM_PER_KEY
#define QUICK_TAP_TERM 0
#define HOLD_ON_OTHER_KEY_PRESS_PER_KEY

#define EXTRA_EXTRA_LONG_COMBOS
#define COMBO_TERM 40
#define COMBO_TERM_PER_COMBO
#define COMBO_MUST_HOLD_MODS
#define COMBO_HOLD_TERM 50

#define ONESHOT_TIMEOUT 3000
#define CAPS_WORD_IDLE_TIMEOUT 3000
#define NUM_WORD_IDLE_TIMEOUT 3000
