VPATH += keyboards/gboards/
SRC += arasaka.c

CONVERT_TO = elite_pi
BOOTMAGIC_ENABLE = no

MOUSEKEY_ENABLE = yes
KEY_OVERRIDE_ENABLE = yes
TAP_DANCE_ENABLE = yes
COMBO_ENABLE = yes
HOME_ROW_COMBO_ENABLE = yes
CAPS_WORD_ENABLE = yes
NUM_WORD_ENABLE = yes
SUPER_TAB_ENABLE = yes

OLED_ENABLE = yes

RGBLIGHT_ENABLE = no
RGB_MATRIX_ENABLE = yes
