name: Build image

on:
  workflow_dispatch:
    inputs:
      qmk_version:
        required: true
        type: string
        description: qmk/qmk_firmware version
        default: master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/setup-buildx-action@v3

      - uses: docker/metadata-action@v5
        id: meta
        with:
          images: ${{ github.repository }}-base
          tags: |
            type=semver,pattern={{version}},value=${{ inputs.qmk_version }}
            type=sha

      - uses: docker/build-push-action@v5
        with:
          push: true
          build-args: |
            QMK_VERSION=${{ inputs.qmk_version }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
